### ISSUE TITLE
Minor QoL improvements - make it fool prove

### ISSUE THREAD

**Issue by philipp2310** [imhotep/hass-unifi-access#1]
First of all - THANK YOU!

Second, please don't see any of the following points as critique. All of it should only happen when Users behave like they never saw a PC before and I'm willing to adjust most of the stuff myself if you want to focus on the important parts. I'm just writing down all possible minor flaws, as I would do for my own software. Nothing has to be fixed for an alpha state.

Opening the door is working fine, but I don't have a physical contact sensor so far, so I can't talk about that. Will tinker with that sensor later in the evening I guess.

Now, while setup is as easy as it can get, I still managed to mess it up.

- [x] I copied the IP of the Access HUB, not my Dream Machine.

Maybe clarify in the instructions or exchange the error message to make sure to remind about the correct IP?
`socket.gaierror: [Errno -2] Name does not resolve`
This is mapped to unknown error in the setup window

- [x] I copied the IP of the DM including https:// into the host.
Obviously that is not working when asked for the host.
Same error as before because it tries to resolve https://https://192..
Would be a small quality of life improvement if there is a quick check "is starting with http*? then remove that part" - or the same error message as above

- [x] I didn't give enough permissions on token creation (unknown error)
Should require edit for devices at least I guess -> Instructions

- [X] I added it multiple times to increase the permissions and try again:

`Platform unifi_access does not generate unique IDs. ID e9728ff1-abcdef... already exists - ignoring lock.XYZ`

I guess the given ID is unique to the door, so there really is no reason to add it more than once.
No real issue, but maybe it is possible to catch during setup the duplicate IP? I have no idea about the inner workings of HA, so this would be the only thing that I can't address myself. And I never saw any other integration that is catching this kind of user error.

- [x] Unlocking and then quickly unlocking the door is throwing an error.
This might be caused by my previous double installation as the error looks more like a permission error, but the current token has full permissions:
`Could not authenticate with https://192...:12445. Check host and token. URL: https://192.168.1.1:12445/api/v1/developer/doors/e9728ff1-abcdef/unlock
Could not authenticate with https://192...:12445. Check host and token. URL: https://192.168.1.1:12445/api/v1/developer/doors/e9728ff1-abcdef/lock`
As the door is locking itself after a few seconds anyway, that's not a real issue as well.

**Comment by DefenestrateIT** [comment]
I'll second, "First of all - THANK YOU!"

It does throw an error if you try and lock/unlock/lock/unlock rapidly.


```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:226
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:27:46 (5 occurrences)
Last logged: 18:31:58

[546913862464]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 99, in _async_lock
    await entity.async_lock(**remove_entity_service_fields(service_call))
  File "/config/custom_components/unifi_access/lock.py", line 62, in async_lock
    await self.hass.async_add_executor_job(self.door.lock)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unifi_access/api.py", line 161, in lock
    self._api.lock_door(self._id)
  File "/config/custom_components/unifi_access/api.py", line 87, in lock_door
    self._make_http_request(
  File "/config/custom_components/unifi_access/api.py", line 111, in _make_http_request
    raise ApiError
custom_components.unifi_access.api.ApiError

```

**Comment by imhotep** [comment]
Thanks for the feedback!
I've addressed the following
- hostname field: you should be able to enter it however you like now (including with port)
- I did update the README to include some more info on what host/ip to enter and what kind of token to generate.
- locking actually is not supported by the API but you probably have it set to automatically lock after a short delay.

You should be prompted for an update when you reload HACS.

**Comment by DefenestrateIT** [comment]
Lol you're right, I could have sworn there was; when I skimmed over the API documentation the other week.

But that new update fixes it well.
👍
