### ISSUE TITLE
Lock not showing up in Apple Home app with HomeKit bridge

### ISSUE THREAD

**Issue by larstobi** [imhotep/hass-unifi-access#11]
Thanks for this plugin!

I've been trying to get control of the Unifi Access lock using the Apple Home app,  by using the HomeKit bridge integration in Home Assistant. I have selected the lock.myentityname and added it to the HomeKit bridge configuration in HA, but only the Door Position Sensor show up in Apple Home, and specifically not the lock function. 

Has anyone gotten this to work? Is it supposed to work?

hass-unifi-access version: v1.1.1
home-assistant version: 2023.11

**Comment by imhotep** [comment]
@larstobi I am not super familiar with HomeKit but have you read the considerations [here](https://www.home-assistant.io/integrations/homekit/#considerations)? Bridge has to be set to **ACCESSORY** mode for Lock entities

<img width="686" alt="configure" src="https://github.com/imhotep/hass-unifi-access/assets/93032/7d8c72bb-b719-452b-b327-ba4812cda1c6">
<img width="602" alt="accessory" src="https://github.com/imhotep/hass-unifi-access/assets/93032/14b52ce3-b386-435d-b51c-fcd05b297213">


I did try it and it seems to work just fine. This does mean that you will only get your lock for a given homekit bridge but you can create multiple bridges in home assistant if you want to support other entities.

I am closing this issue but feel free to re-open it if you run into any more issues.

**Comment by larstobi** [comment]
Thanks so much, imhotep! I was not aware of this consideration, and indeed it worked perfectly. Thanks again!
