### ISSUE TITLE
Answer Doorbell and View camera

### ISSUE THREAD

**Issue by bvsputnik** [imhotep/hass-unifi-access#14]
Hi, would be great if you could answer the Doorbell like on the Unifi Access app, and view the doorbell camera before unlocking. And also to have the doorbell chime come through HA on the android tablet speaker

**Comment by imhotep** [comment]
Unifi Access video feed is unfortunately not available via the public API
As for doorbell chime, you can easily create an automation to support that. Use the doorbell_pressed binary_sensor as a trigger when set to **true** triggers an action like play an audio file (chime) on a **media_player** (tablet, speaker, etc…).
