### ISSUE TITLE
doorbell pressed event not displayed

### ISSUE THREAD

**Issue by treehousechampion** [imhotep/hass-unifi-access#15]
First off, sincere thank you for development here. Really cool integration and as I build more with it, I'll submit some pull requests.

In attempting to add a simple automation that triggers from the doorbell press, I cannot seem to find the doorbell_pressed event. Is there something I am missing here?

<img width="600" alt="Screenshot 2023-12-18 at 6 33 31 PM" src="https://github.com/imhotep/hass-unifi-access/assets/154115017/4d42d827-9a24-4a3b-a038-321a805a2d52">

**Comment by imhotep** [comment]
@treehousechampion doorbell_pressed is a binary_sensor entity of type OCCUPANCY. So in your case, you want to: Do something when Front Door Doorbell became occupied -> This translates to somebody just pressed the doorbell. The binary_sensor will remain true while the doorbell is ringing and become false when the doorbell is either answered or cancelled. Hope this helps

**Comment by treehousechampion** [comment]
Thanks, super helpful. I am admittedly new to HA and still familiarizing with the YAML structures.
