### ISSUE TITLE
Feature Request: NFC/PIN Authorized Event as Trigger

### ISSUE THREAD

**Issue by dirkgiessamer** [imhotep/hass-unifi-access#17]
First of all, great work, much appreciated!

My use case would be that if the G2 Reader Pro „grants“ access to a user (via NFC or PIN, does not matter) this could be used as a trigger to do other stuff in HA (like unarming the alarm system). Quite similar to the „doorbell_pressed“ trigger a kind of „user_authorized“ trigger would be great. And even better to get the userID passed on to i.e. start a different scene on entry to the house for a certain person (play different welcome music etc).

**Comment by imhotep** [comment]
I like this idea! Would it be like a "last_authorized_user" [text entity](https://www.home-assistant.io/integrations/text/)? I'd have to check whether we get user info events on unlocks but if we do, it should be pretty straightforward.

**Comment by dirkgiessamer** [comment]
Yes, as long as we get this info right away kind of „onUnlock“ and start an action, that would be perfect!

**Comment by FermedePommerieux** [comment]
This would be extraordinary to be able to do that.

**Comment by imhotep** [comment]
https://github.com/imhotep/hass-unifi-access/releases/tag/v1.1.3-beta

If you could help test it and report issues, I'd really appreciate it!

**Comment by dirkgiessamer** [comment]
Installation worked, the Logbook shows events (see screenshots), the events entities though show up as unavailable...
Let me know what to do to help!

<img width="1233" alt="Screenshot 2024-01-17 at 10 22 39" src="https://github.com/imhotep/hass-unifi-access/assets/28338455/de5f497a-f14d-422f-829a-d13c267dac29">
<img width="988" alt="Screenshot 2024-01-17 at 10 22 45" src="https://github.com/imhotep/hass-unifi-access/assets/28338455/33fa230c-5964-48f7-bc36-06d9288bc49c">
<img width="1066" alt="Screenshot 2024-01-17 at 10 22 50" src="https://github.com/imhotep/hass-unifi-access/assets/28338455/f66d5208-30e6-453f-be6b-97667bc80bbd">

**Comment by imhotep** [comment]
Have you tried opening the door or pressing the doorbell? Can you share some logs?

**Comment by valerix85** [comment]
Hi guys, I've installed this morning without any issues 

![image](https://github.com/imhotep/hass-unifi-access/assets/52428493/a8ad5c37-e429-4e6e-ae26-0c89c0af369a)

I've open a ticket on UniFi asking for the live stream via API if the doorbell is pressed, I'll keep you updated

**Comment by dirkgiessamer** [comment]
> Have you tried opening the door or pressing the doorbell? Can you share some logs?

Yes, I did, doorbell as well as NFC opening the door - just checked again and now it works!

<img width="936" alt="Screenshot 2024-01-17 at 22 33 50" src="https://github.com/imhotep/hass-unifi-access/assets/28338455/282bf352-8602-40b0-9ac3-0f37dda4e8ef">
<img width="970" alt="Screenshot 2024-01-17 at 22 34 12" src="https://github.com/imhotep/hass-unifi-access/assets/28338455/eb54f444-0665-4317-9dc5-f5735ad76638">


> I like this idea! Would it be like a "last_authorized_user" [text entity](https://www.home-assistant.io/integrations/text/)? I'd have to check whether we get user info events on unlocks but if we do, it should be pretty straightforward.

Did you check on this idea? To get the authorized user?

**Comment by imhotep** [comment]
Yes! It's in this release. Go to Developer Tools > Events > Listen to events and type one of these events then click on Start listening.
- `unifi_access_entry`
- `unifi_access_exit`
- `unifi_access_doorbell_press_start`
- `unifi_access_doorbell_press_stop`

You should get some metadata when the event fires that gives you info on who entered or exited a door. It will be in the `actor` field.

**Comment by ttjorvi** [comment]
hi, just trying this integration and it looks pretty good. 

Wondering if it would be possible to get the NFC friendly name or id as well as the actor in the event notificartion in the case where an actor has many NFC cards.

**Comment by filip-heens** [comment]
> Yes! It's in this release. Go to Developer Tools > Events > Listen to events and type one of these events then click on Start listening.
> 
> * `unifi_access_entry`
> * `unifi_access_exit`
> * `unifi_access_doorbell_press_start`
> * `unifi_access_doorbell_press_stop`
> 
> You should get some metadata when the event fires that gives you info on who entered or exited a door. It will be in the `actor` field.

Hi Imothep, I'm quite new into this part of the HA. (for now I always created the automations with "standard" building blocks ;-)
When I go into the listen mode I do see the actor filled out as supposed, but do you have a link with examples on how to use this when e.g. the actor is user x then do action y

**Comment by DaleJP** [comment]
Hi,
THANK YOU for this integration!
Does this feature mean that I can have automation based on the card that entered the door?

I run a small nursery and preschool, and I want to log pickups and dropoffs using the data from Access. I'd like to be able to display avatars of the kids on the Classroom Dashboard, the number of children in the building for emergencies, and log the children's attendance. Having a trigger to work with from the Access API telling me who has entered and exited would be phenomenal.

**Comment by DaleJP** [comment]
This is fantastic. I have just successfully triggered an automation with the event.

![image](https://github.com/imhotep/hass-unifi-access/assets/95194110/44b5c8d1-18e6-4605-9b62-cb5878eedb78)

I have managed to trigger a notification when the user enters the building.

Superb work.

**Comment by filip-heens** [comment]
Thanks DaleJP!!!
It works... 
for your "problem"
if you inclide the door_id or the door_name it should do the trick.
I only have one Acces Reader, so I can't be 100% sure, but think that should do the trick

**Comment by DaleJP** [comment]
You have no idea how happy this integration has made me. I had an esp32 hooked up to the door to get doorbell notifications before.
I mean the "id" field under contexts. They are all different readers on the same door.
![image](https://github.com/imhotep/hass-unifi-access/assets/95194110/c50f676e-de4f-4b58-a7e9-f938e0af7d4d)

The inside reader is registered as "Exit" in Access and the outdoor ones are "Enter" but they both fire the event as entry.

**Comment by filip-heens** [comment]
I think that's, because you "enter" the door/gate when leaving in the opposite direction as you "enter" the door when "entering" (if you understand me ;-))

**Comment by DaleJP** [comment]
All of the readers show up as entry in the integration, whether inside or outside. It could be the API that's messing up. I know it's pretty new.

**Comment by filip-heens** [comment]
Dale, what I mean.

You Enter the building via entering the door/gate
You leave the building via entering the door/gate  in the opposite direction.
That’s why I think they are saying “entering” (or I misunderstand what you are trying to say, that’s also a possibility &#128521;)



. . . . . . . . . . . . . . . . . . . . .
Filip Heens  ICT Consultant
[data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALIAAAA0CAYAAAAuY2KtAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFxEAABcRAcom8z8AAC2ySURBVHhe7Z2Hd1bVtvbzr9xv3HuP93iUFkhIQnohEEgPIQmhg2DvvaNi9xw7UqVKB0XEjtixHOxdRHqREkI6887f3Jm8K68RUfB+njOYgzX23quvuZ75rLnW3nlJkKMirS1HpelIh7S3i4pGSJuGZg2NGg5Lx9EGDYc1pakzrUOfxfK36+PRDo1SOXr0qLS1NUtL62Fpa6fcEY1t1dAuHR3U3655yBwFza2BdOr0q99Hob2jSes6ouVatO4j2s8GfW7S+lq0nUZLa9f71tYW7YsN4JjQZlNTkzQ2NkpLS4s9nwphnNR35MgRbbfVnl24p50w7t9BfFwnMra2tjY5fPjwMZ03NzebnrhnLtDbqdZPAphqb1U4KZi1HRUaAEwxIB9VEGsXFJhNes/EKTA1G31xELt0dCj4FGjtHY3S2tagAUBTpjsg6zNgVpC2dzQbKAFrBNRmi1fI2DUCNQo5ovU1a13N0tRM/Ty3Wd1trW2mNBSFEi1OlYoSo7aPWuAepf5W8fJeB3V7vQh1enu/p/4/q3Q3VpdQF4zbg+ufdNfHHwrkdiW+DsVth5JZVDcTBRvGgMz1qMB8ClAFULsWsI7wT+ero10H0+bWCisqcJW9W1oPSnPLIY2nvsii29ujfACZAJgBKOza1HxI8ys4FazE0Q+Yl2AGZGCO7gE7QGYFsI6ooLCGhgbZv3+/KSxqR1O1r4So/UjpnnaiQnnKdleOeA/hJP67CPryMTF+D65X0iEQDw5c0hDKuf5Jpy4vS9ypkIQmxWobhBe1qRUz0cqIyr6i4I3ADBMDYl1KFTjt6k8cVUoGxK0tHXK4oUUaDh1RSyMPbM4kAkAHZNTZDi3TqqzJwH2QNNyuQG9uOaIBV4G2vQ4U1KjL1CEtp/UA+nbqBdBYPu1FRoKECg3bQFnxLBFr/8SE/F42FJ69TdohdJfvX1l8XIwJveKuEdCppzPmMJAvLEOc5w3jqeNU6CqhsUHBGCM1bRBQ4eNGAI7ADJCZKNg4chPIz6VN3ZLGxhYFM/5rBHJASF78ZBhcu6+B/Nr5Vh2khk5sm1BfWxvLP4oBdOo2NKnLoMzf0tKkBqIA13QapX4zJGX+o2p0secInKFS/BnFoTACCnVF/hYJ6+bqk0PAHyT81jr/FYVxY7QAmftQXM8QBtcQsIRQP9yTzwngZCVi5BipaYNaeSeQcQ/YsEWbPGibjkedc0bGk8C1IFgcacqo0dJ/UAfcoODvHLC2wVhwY8A7RspzFKKyiLsHbq2uEE+PGD66R0EtLRjQz1mQcmFZAs+UORnl0VbohwNi+nwydf6ZxfXmEurThXv0il4AeSikudF7Ga4O5LCe3ysJuBWA0dhSOwIb4g506AYL94INGxu3CMSdHWjuUPZtl6bGdmlp0k6qIRi2NOA+wKTGyLoRa1F/t6VFfVr1oV0AckszJyVavoVlKAZuGB5mb1I3pUP9aXzq5uYWqwNFxIsrxBUYr3Ce4xXVXdyJCGW8TibAGZ52Q58c+b1t/NmEMRyPOcGMEwN5Q7CGQryzNBLWeyr0lOAABMhU2qzs5kdibO4AMr4uG6xo6Q+EcnHYciBz0sAmjWUfkP5eaW1lp4tP1qIsf/yKfk0hKNEV/luVRzkHLmXDCfNJ8no93SftX1kYC4BzkuCZK+OLiC9y2TyNePIePHhQ9u7daysr5T0v6V4vz6Rxf7ISAVnrgf3oQHNzdMQGkKNjMZaJVk07LDu2b9fO/WQnFIRWZVX8a/Mcgr7oUI3Vm5sj3/FwQ7McORyxd0ebTjRg1yvM3qqBe1wT7hsbNJ/W26YAbjjUbBvJ6EQkxoaHDzfKrl17ZMeOXbqkR74pCsIQYWZCPINwHyozTDsR8fop3534ZFAv4VRMzp9FXO/xegaEPBOPbn/66SfZvHmzfPDBB/Liiy/KihUr5OWXX5YtW7ZYGc/rwjPlToWuEowttR6ATGNsrhzIAFi7aBn27d0jr768XubMni+zZsyVBfOXyuqV6+SlF96Qje9sku+++VEO7G8wkCKw8pGmg/Ltt9/K8+tekTmzFsv0afNl9syFsmjhclm25GlZtGCFzJ+7TBYvWikrlq+xuDmzlsgT0+ZpGwtk2dI18vmn31r/ENyMPbv3yQfvb5KlS1bIjOmzZNGixbJ27Vp5+umnZfny5fLUU0/JwoXaxqJFsmbNGnnnnXdk27ZtpnTk9wKNMoAYxbtQ56FDh47VjXj9/46CztCBE0UITJj33Xfflblz58ptt90ml156qZxzzjl2/9Zbb3W7Geb5985HvCTgl9qmTQHIhPCGzM5seRlhLyKiSfnyyy/lrjvvk+IhVZKdOViGDBoutcMnyoSxl8gVl90sjz48R17fsFF+2nvA8iP4x5s2bZJ773lQqirHaLmhkplepHXUyvBhE6S0uF4KC6qkuKhWavS5pnqiDC4cJqn9B0p2xlA5Z8Kl8vxzrxxzTZqbWmXr1p3azlvy0IOPyqRJ50ldXb2MHTtO7yfLtddeK3fddZfcc889ct1118kFF1wgV199tSn3k08+OamTBVe6l2cSYRrq3bdvn8UhpJ/spPwZxcfv7kA8+HAjXn/9dZk2bZpcdNFFUlxcLAMGDJDx48fLc889Z5thxOvxsvHPv1cSOLEAKL7Z86MtQMhmTadMG2qXV155VUbUjZazz+on/RKzJa3/IOmfNFB6np2pIV2KBlXLHbc9IO+9u8n8WYTThc3fb5Z5c5fI6JEXSL8+uXLmGf0lJalQ8nIqFbBF0vOsTEnslSuZA0okN6tckhLz5C//1VfOPjNNqirGyqoVa3Uzqcak/440wgbNqrR9suG1NxWsN0pBQaFkZeXImDFjZebMmWY4X331lTH0hRdeKAMHDpRhw4bJ3//+d3n//fePKfRkBDbaunWrvPDCC7Jq1SpbTl1OdkL+jALQCAjjc/B5HAK4MWhWYFbEESNGSFJSkowbN870hNuKUIa8p8qlcDHXIjo+i1E8AATIvGoGQc3NR2TlytUydEi59Dg7WbLSh0pG2lBJ7jtQAZch//n/+ij4EqVkaI3MfGKeTuyWYx0/3NAoX37xrdxz16OSm1kmfXrmSHrqUMnJrJABKcUK7gLp32+Q1llmcanJg6WXGkff3nkK5PGyYtkaaW/B0jjvjilux/bdav3TpaSkTNLSBsiECRPML3NBqfPnz5fa2lpJT09X1h4rs2fPlm+++cbY9LdIvMKpG3fm1ltvNQP57rvvOlNOTmgHxgsBcqJysqCgfLQid78HOJ7E6/O9996T8847T1JSUmxe8JOpG/Exnmg75A9dmF8S+2jIXjErkGOZ2azRcOQfswNdunSFlJfVKHhzjDkBY+aAUr2vUkAOVaZNUabOkiuvuFE2bHhT9uzZKx22k9QalO1XLFsr5SVjlcmHWLnMAWVqDGV2zcmstHpyMio1rlSBPVgBPUSGVUyUpYufkQ4YGQnmd9fO3TJ/3gIFap0ycpb6YxNNYaF8//335mYUFhbK4MGDzd148803jVERlInBAcwff/xRfvjhB91E7jIXhDTXB1cYBDYnL3XcfPPNUlVVJVdccYU9E0/YvXu3HDhwwOrFl6SMl9uzZ4/VTRp5du7caYF7JpoJc98TMJOXcizbBOqmDo76wonlnv76Rpd0Nl7kZ+6okzapj3jqok3i3Wiow8sj3hf6ThnaJeALE0c+BzBth3uHt99+Wy6++GIlmDRjZAdyjChjfacO+kW99He7HSjstf6Sn0D95AvLxYsBGby1K9hi+TheifnHgHLevKfUp61WIOcq6CokI7VU/dgqGZRfL3nZ1eYeJCnIJ4y/UHerz2iHdmonYg2/+vI7MnHcVQbclKQiA2y2Ajcva5jk5wy3a3Z6pWQNKFcQq3/Vv0SBfE5XIAfjAHALFixQH7lW8vJyVHEXqQFtODYxCAp64oknJDNT3Z+ePc1fe+WVV2yCCF]
Patronale Life NV/SA
Verzekeringsonderneming toegelaten onder code 1642, onder toezicht van de NBB
Bd Bischoffsheimlaan 33
B-1000 Brussel/Bruxelles
Tel: +32 2 4865090  (IT)
<http://www.patronale-life.be/>www.patronale-life.be<https://www.patronale-life.be>

**Comment by ttjorvi** [comment]
Tried it out on my access unit and got the following using one on the NFC assigned to me:

`event_type: unifi_access_entry
data:
  door_name: Cellar
  door_id: d7e39f94-7fdb-4dab-8852-191fc58b0deb
  actor: Thorr Tjorvi Einarsson
  type: unifi_access_entry
origin: LOCAL
time_fired: "2024-02-06T16:45:09.858770+00:00"
context:
  id: 01HNZMY9B2V08XVW5QR55A2CTZ
  parent_id: null
  user_id: null
`
Then with another NFC chip:

`event_type: unifi_access_entry
data:
  door_name: Cellar
  door_id: d7e39f94-7fdb-4dab-8852-191fc58b0deb
  actor: Thorr Tjorvi Einarsson
  type: unifi_access_entry
origin: LOCAL
time_fired: "2024-02-06T16:50:44.989503+00:00"
context:
  id: 01HNZN8GKXE76RKE9QZH5BB2RH
  parent_id: null
  user_id: null
`

It would be good to know which NFC chip was used

**Comment by DaleJP** [comment]
Unfortunately, I think you would need to create a new id for the other card (Like it used to be with multiple cards for one user).
They have encryption etc with the cards so I doubt they will ever expose the raw NFC data. Unifi might expose Card 01, Card 02 or something but I doubt they'll expose the card details over the API.

**Comment by imhotep** [comment]
Sorry for delay, been very busy. I released a new version and updated documentation on how to use the event feature. Looks like you guys have figured it out.
There is no NFC data accessible through the API as far as I can tell. I didn't dig in too much. Closing this for now but feel free to re-open if you have any questions or suggestions.
