### ISSUE TITLE
Issue: Unlocked State reads as "Unavailable"

### ISSUE THREAD

**Issue by johnoldiges** [imhotep/hass-unifi-access#19]
The unlocked state for each door is set as unavailable. I realize this is due to not wanting users to interact with the lock button as that doesn't function yet but shouldn't it still display the status as "Unlocked" or is this a limitation of Home Assistant where it can only be one or the other and not both "Unlocked" but also non interactive until returning to the Locked state.

**Comment by johnoldiges** [comment]
It also appears that when you unlock the door via the entry and exit readers or possibly relay inputs the doors state doesn’t update in home assistant.

**Comment by mtwo** [comment]
+1 to this. On a related note, the Access application added the ability to lock doors that are currently unlocked, though I'm not certain if this is exposed through the API.

**Comment by imhotep** [comment]
This has already been discussed [here](https://github.com/imhotep/hass-unifi-access/issues/10)
There is still currently no way to unlock doors via the API and Home Assistant doesn't provide a way to disable lock entities short of making them unavailable. I understand this is not ideal but I can't think of a better option.
