### ISSUE TITLE
Feature Request: Unifi Access PoE NFC reader for Home Assistant, Settings > Tags.

### ISSUE THREAD

**Issue by DefenestrateIT** [imhotep/hass-unifi-access#2]
I hope you don't mind, but I'm mainly brainstorming here, though it may be of some help to you. And I don't think this is possible at the moment for A number of reasons, but it is not a bad idea to start thinking about it now. But if this can be achieved here, it will be one of the biggest Features of this integration.

Problems:
1/ Do the Cards/Tags/E-Pass need to be registered to A Unifi Access User first to be recognised & passed on to HAss?
2/ Might require A different integration where the NFC Reader is directly interfaced with HAss rather than through the Unifi Access controller (If Unifi would even allow this).
3/ Is there currently an API call for retrieving an unknown NFC ID/Token, & how would the end user extract it in the GUI for quickly registering in Home Assistant Tags?

I have already put in a [Feature Request ](https://community.ui.com/questions/Feature-Request-Allow-Unifi-Access-to-adopt-Access-Readers-with-out-requiring-Unifi-Access-Hub/78ba8e01-78cd-4eb0-995f-e858b46e3306)with Unifi to make this more feasible.

**Comment by imhotep** [comment]
1) Home Assistant cannot have any knowledge of the NFC cards used in Unifi Access as far as I can tell. All we can do is create a service to enroll a new NFC card (or remove/unassign a card after enrolling it) but you'd have to go to your Unifi Access reader to scan it for enrollment.
2) One thing you can do is scan an [NFC tag](https://www.home-assistant.io/integrations/tag/) with your phone or scan an NFC card with a [tagreader](https://github.com/adonno/tagreader/tree/master) and create an automation to unlock a door that way but then you wouldn't see the user activity in Unifi Access. Instead, you will see it in Home Assistant. In Unifi Acess, it will show that all door activity comes from `Open API`
3) I don't think so and I doubt they'd ever allow it for security reasons. They barely allow third party NFC cards and you have to select a special option in the settings to enable them.

**Comment by DefenestrateIT** [comment]
> 6.3 Fetch NFC Card Enrollment Status
>This API enables you to poll a UA reader to fetch the NFC card enrollment status and the generated card
tokens.
>Request URL: /api/v1/developer/credentials/nfc_cards/sessions/:id

I'm interested in the ID, not the token.

To be clear of my intent, **IF** Unifi allows the NFC lite to be adopted by Access without requiring it to be assigned to A hub. The end user could use them as PoE-powered NFC readers around the house. I know you can use your phone or Build-it-yourself reader, but there aren't any PoE Readers available (that I know of), & anyone who has invested in PoE wants to utilise it as much as possible. This would be A hack (unintended purpose) of the Unifi Access system, but it would benefit everyone all around, Unifi would sell more products & the home automation community would have another great product.

One of my greatest interests in Home Automation is its ability to help the physically impaired, NFC is a very valuable tech that  IMHO is underutilized. Imagine a blind person, having NFC tags attached to everything (Paperwork, Food, Ect...) so that that item can be scanned to trigger an automation.  Their phone isn't necessarily the best option & there aren't a lot of NFC readers available for HAss...

**Comment by imhotep** [comment]
I don't think you can just adopt a UA lite outside of Unifi Access. I haven' t seen any references to it.
You can make almost 3 PoE readers for the cost of one UA Lite and not be tied to Unifi at all. Here's what you need:
[ESP32 POE](https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware)
[PN532 NFC](https://www.elechouse.com/product/pn532-nfc-rfid-module-v4/)
3D Printed case(https://www.thingiverse.com/thing:5474964)
You can run ESPHome on this and do everything you just mentionned.

**Comment by DefenestrateIT** [comment]
I concede to your suggestion, it is a better method to approach this feature.

It is hard to get ESP32 PoE where I am, but doable & a lot cheaper.

Please close this Issue.
