### ISSUE TITLE
Integration sometimes has to be reloaded to find UNVR

### ISSUE THREAD

**Issue by mtwo** [imhotep/hass-unifi-access#21]
Hi! This integration is fantastic, thanks for providing it!

After roughly half of my Home Assistant reboots, the Access integration fails to connect to Access on my UNVR. Reloading the integration on the integrations page fixes this. The Unifi Protect integration always succeeds in connecting to the UNVR, so perhaps they're retrying more aggressively or have some kind of discovery mechanism that could be used here.

My UNVR has a dynamic IP address (I'm using both NICs on it and Unifi Network will only let me assign a static IP to one of them) and this integration is connecting to it via its hostname. This may or may not be related.

**Comment by imhotep** [comment]
@mtwo can you provide some logs when you're facing the issue? The integration attempts to connect to your Unifi Access websocket server every 5 seconds and automatically tries to re-connect on connection failures. You can also try using polling (but you would loose the doorbell press feature).
There is currently no discovery mechanism. You have to specify a Host/IP and API Key. If those details change, you have to reinstall the integration unfortunately.

**Comment by mtwo** [comment]
Yep, I'll post logs the next time it happens

**Comment by mtwo** [comment]
I thought that I was able to reproduce this, but I discovered that the entities fixed themselves after a minute, Apologies for the distraction!
