### ISSUE TITLE
Support door locking

### ISSUE THREAD

**Issue by kristian-gausel** [imhotep/hass-unifi-access#22]
The new unifi access seems to support a way to lock the door again. I haven't looked into how it is done, but I know it is possible to trigger a door lock event in unifi access.

It would be great to add support for unlocking (and leaving unlocked) and locking the door again.

**Comment by imhotep** [comment]
Unfortunately, there is still currently [no way](https://github.com/imhotep/hass-unifi-access/issues/19#issuecomment-1891032065) to LOCK a door via the official API as of version 1.22.17 of Unifi Access.

**Comment by KGausel** [comment]
I was thinking especially having options for "Leave unlocked" and then locking again.

It seems you can PUT to `/proxy/access/api/v2/device/<device-id>/lock_rule`
(This is from the web interface, I haven't looked into if it is done differently in the integration, sorry)
with
```
{"type":"keep_unlock"}
```
to keep the door unlocked and then again with
```
{"type":"reset"}
```
to lock the door.

**Comment by imhotep** [comment]
@KGausel this is not part of the official API which means it may break without notice. There are definitely a lot of features that could be supported by using undocumented APIs (such as camera feeds etc…), I just don't have the bandwidth currently to work on them. I welcome Pull Requests though.
