### ISSUE TITLE
Camera Feed

### ISSUE THREAD

**Issue by filip-heens** [imhotep/hass-unifi-access#24]
Hi Finally found time to install the custom application and it looks like it's working...
The only thing I'm missing is the videofeed from the Access G2 Pro (also don't see the Access Pro itself under devices, only the hub, but maybe that intended?)
Is this not yet implemented, not possible or ...?

**Comment by filip-heens** [comment]
If you want me to do some testing... just shoot

**Comment by imhotep** [comment]
This integration is specifically for managing door access (lock, unlock, doorbell, view status, etc...)  not device management (like unifi access readers or hubs). 
The video feed is currently not supported by the official API as discussed [here](https://github.com/imhotep/hass-unifi-access/issues/18) and [here](https://github.com/imhotep/hass-unifi-access/issues/16)

**Comment by filip-heens** [comment]
sorry, kind of new to github ;-) didn't know I could also read the closed threads...
testing offer still stand though ;-)
