### ISSUE TITLE
Door Position sensor status changes to open but immediately returns to closed

### ISSUE THREAD

**Issue by rossbarichievy** [imhotep/hass-unifi-access#26]
Firstly thank you for all the good work. 

I have noticed the door position binary sensor does not accurately reflect the state of the actual sensor. In unifi access the status of the door position sensor follows the actual door. In home assistant the sensor logbook shows that the status immediately returns to closed after an open event. Because of this the following physical closed event is not captured.

Home Assistant timestamps
![image](https://github.com/imhotep/hass-unifi-access/assets/129482933/bb0ab890-56ee-4c46-8d29-6c77b686f96b)
Unifi Access timestamps
![image](https://github.com/imhotep/hass-unifi-access/assets/129482933/2f98c6cf-f3b0-4e43-a3ed-5ac7e9c7c833)

**Comment by imhotep** [comment]
Yes, the API doesn't seem to be reflecting accurately the status of the DPS sensor :/
However, there may be a small bug where the DPS binary_sensor quickly toggles from Open to Close and back to Open, stays open and then switches to Close again. Do you observe that @rossbarichievy ?

**Comment by rossbarichievy** [comment]
When looking at the DPS binary_sensor logbook it only shows the state changing to open for 1 second then back to close and remaining closed until the next door open event.

**Comment by imhotep** [comment]
@rossbarichievy do you have a door strike or magnetic lock? Do you mind sharing some logs? I am not observing this on my end.

**Comment by rossbarichievy** [comment]
The sensor is a NC magnetic reed switch that is not part of the lock unit. I will get some logs and send them to you.

**Comment by rossbarichievy** [comment]
Thanks again for your help @imhotep. After doing a bit more digging it seems that the unifi access hub was not consistently reading the door position sensor. There must be some logic in the hub to detect that wiring is connected and the wire I was using on my test bench was not enough to ensure the blue DPS light stayed on. The hub would read the changing states of the switch and looked correct in the access application but behind the scenes it was throwing out the value because it appeared nothing was connected, hence the API payload was empty.
