### ISSUE TITLE
Trigger request to exit?

### ISSUE THREAD

**Issue by cregeland** [imhotep/hass-unifi-access#28]
Hi,

Great job on this integration - thanks!

Would it be possible to trigger a request to exit through the API?

Use case: I have a multifunctional wall panel/button in the hallway that I use to trigger the door unlock. Every time I trigger the door unlock the Access Reader Pro G2 will say «welcome». Not a big deal but I notice when the dry REL contact on the Access Hub is closed the door will simply unlock without a greeting. That makes more sense when unlocking from the inside😁

**Comment by imhotep** [comment]
@cregeland what do you mean by a "request to exit"? Do you mean unlocking the door without the "Welcome" message? If so, no, it is not possible. The API only supports unlocking a specific door. No additional settings are supported.

**Comment by cregeland** [comment]
Thank you for your reply. I was hoping the API would support unlocking the door using the «request to leave» function. This would be the same as when a user waves in front of the Unifi Reader Lite to unlock the door from the inside. 

The same functionality is available when closing the dry switch on the Hub labeled «REL».

The result is an unlocked door with only the a short sound played outside on the access reader pro - no speech.

**Comment by imhotep** [comment]
@cregeland unfortunately, the API only has an unlock functionality :/ Nothing that would mimic the Request to Exit/Request to Enter you'd get with a button/motion sensor/access reader etc…
I would request it in this [thread](https://community.ui.com/questions/Unifi-Access-API-e-g-for-Home-Assistant/35d79805-bf4f-458a-892f-ad1f72c07259?page=4) in the unifi forums. The support staff usually watches those messages.
