### ISSUE TITLE
DPS status

### ISSUE THREAD

**Issue by mrcppp** [imhotep/hass-unifi-access#29]
just deployed your (great!!) add-on on my testing HA install. I'm interested on being informed on door position, but got a strange behaviour: while in Ubiquiti's Access logs DPS is -correctly- marked as open, sensor in HA is triggered open for few msecs, then turns again to closed.

![Clipboard Image](https://github.com/imhotep/hass-unifi-access/assets/124896515/a8b9dc92-b8d6-40bb-8731-795dadc9f3e1)

last action reported in log, and how status is shown in HA:
 
![Clipboard Image (2)](https://github.com/imhotep/hass-unifi-access/assets/124896515/f9559215-379a-48ac-b1c7-391c3c59c0b0)

![Clipboard Image (1)](https://github.com/imhotep/hass-unifi-access/assets/124896515/540eac8f-8e11-4877-a4b9-641010a3ddd8)

**Comment by imhotep** [comment]
@mrcppp do you mind sharing some logs when opening a door?
