### ISSUE TITLE
Feature request - Auxiliary support (Siren & Chime)

### ISSUE THREAD

**Issue by mcnijman** [imhotep/hass-unifi-access#33]
I don't know if it is possible to trigger these from the API, but if so, that  would be a nice feature to implement.

**Comment by imhotep** [comment]
@mcnijman Could you be a little more specific? What is it exactly that you would like to achieve?

**Comment by mcnijman** [comment]
The access hub has the ability to connect auxiliary devices. Either a door opener, siren or chime. That is on top of the lock functionality, see attached image under AUX. It would be great if they could be triggered from home assistant, but I don't know if this is possible. I just downloaded the API documentation and it doesn't mention either siren, chime or aux.
<img width="376" alt="Scherm­afbeelding 2024-05-08 om 10 06 54" src="https://github.com/imhotep/hass-unifi-access/assets/888707/fba298ba-b8ff-40fa-83ca-3029d1850f7d">

**Comment by imhotep** [comment]
Yeah no mention of this in the documentation :/ I actually would love to be able to enable/disable the siren for example. There is an undocumented API to do that but I don't want to add it to this integration as it may break without notice.
