### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by aLAN-LDZ** [imhotep/hass-unifi-access#36]
Hi 

I provide the correct ua-hub ip address and the generated API token, unfortunately I cannot connect

**Comment by imhotep** [comment]
@aLAN-LDZ can you provide some logs please? What version of Home Assistant are you using?

**Comment by aLAN-LDZ** [comment]
hey, I'm on a business trip now. I will try to provide the required data by the end of the week

**Comment by aLAN-LDZ** [comment]
All clear. The reason was the early access setting in the access application
