### ISSUE TITLE
Send cancel request.

### ISSUE THREAD

**Issue by github-admin-pl** [imhotep/hass-unifi-access#37]
Hi, 
Is there a way to send a cancel request to the Access_reader_pro
I explain, when someone rings the bell, I can open the door via the app or HA and then the chime (and access reader) stop ringing.
But when I'm near the door, I just open the door, but then I need to go outside to cancel the ringing via the Access_reader_pro.
It would be nice if I could cancel the ringing...
I have a sensor that can see when the door is open or closed, so if the door opens I could stop the ringing...

**Comment by imhotep** [comment]
Sadly, it is not supported by the Access API. Can't you just open the access app and hang up on the call?

**Comment by imhotep** [comment]
The `unifi_access_doorbell_stop` is an event triggered by the integration to let you know that the doorbell is no longer ringing. Either cancelled or answered. There is currently no documented way to remotely cancel a doorbell request :/
