### ISSUE TITLE
Feature request: Decline/End Call

### ISSUE THREAD

**Issue by philipp2310** [imhotep/hass-unifi-access#38]
Hi,

would be wonderful when there was a way to end the currently incoming call/ring.

For example when the door was opened without anybody answering the call, it still continues ringing for the full minute.
If that service was provided you could attach an "end call" to the door opened event or at least have some button in home assistant to manually decline it afterwards.

Thanks again for your nice integration, we are using it every day!

**Comment by imhotep** [comment]
Hi, sadly it [is not](https://github.com/imhotep/hass-unifi-access/issues/37) currently possible.

**Comment by filip-heens** [comment]
Hi Anis,

First of all I really love your implementation 😉
But as it seems, I’m not the only one asking for this.
Is there a way (or location) where we could ask this to be implemented in the API.
Maybe if enough people ask it, UI could implement it?

Filip Heens
ICT Consultant
Tel: +3224865090
[Patronale Life b.png]
Patronale Life N.V.
Verzekeringsonderneming toegelaten onder code 9081, onder toezicht van de NBB
Entreprise d’assurance agréée sous le code 1642 - Sous la surveillance de la Banque Nationale Belge
Bld. Bischoffsheimlaan 33, B-1000 Brussel / Bruxelles
www.patronale-life.be
 This e-mail and any attached files are confidential and may contain information which is protected by intellectual property rights. If you are not the addressee named above any disclosure, reproduction, copying, distribution, or other dissemination or use of this communication (including any attachment) is prohibited. If you have received this e-mail in error, please notify the sender immediately and destroy this e-mail and any copies from your system. E-mail transmission cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, and shall have no liability for any loss or damage suffered by the user, which arise as a result of e-mail transmission. The sender is validly committed only if the content of this e-mail has been accepted in writing and signed by an authorized representative, in accordance with the applicable rules on the delegation of powers.

**Comment by philipp2310** [comment]
@filip-heens you could add your request in the UI forums, for example here:
https://community.ui.com/questions/Auto-cancel-call-after-X-Seconds/d3e1ce8f-b776-4a92-ba71-a708fec41aa8#answer/bbbd4a06-33df-46e6-9a59-42a167e10d10

They seem to actively read it and at least a few times I saw "I'll relay the request to our development team", no idea if ever something came out of that ;)

**Comment by filip-heens** [comment]
Thanks, I added a comment 😉
I hope they read it and do something with it 😃

Filip Heens
ICT Consultant
Tel: +3224865090
[Patronale Life b.png]
Patronale Life N.V.
Verzekeringsonderneming toegelaten onder code 9081, onder toezicht van de NBB
Entreprise d’assurance agréée sous le code 1642 - Sous la surveillance de la Banque Nationale Belge
Bld. Bischoffsheimlaan 33, B-1000 Brussel / Bruxelles
www.patronale-life.be
 This e-mail and any attached files are confidential and may contain information which is protected by intellectual property rights. If you are not the addressee named above any disclosure, reproduction, copying, distribution, or other dissemination or use of this communication (including any attachment) is prohibited. If you have received this e-mail in error, please notify the sender immediately and destroy this e-mail and any copies from your system. E-mail transmission cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, and shall have no liability for any loss or damage suffered by the user, which arise as a result of e-mail transmission. The sender is validly committed only if the content of this e-mail has been accepted in writing and signed by an authorized representative, in accordance with the applicable rules on the delegation of powers.
