### ISSUE TITLE
Incompatible with Home Assistant 2024.6.1 due to python request library version

### ISSUE THREAD

**Issue by jdgiddings** [imhotep/hass-unifi-access#39]
HA 2024.6.1 updates the python requests library to 2.23.3. This causes the Unifi Access integration to be unable to load

```
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 2:57:17 PM (3 occurrences)
Last logged: 2:57:35 PM

Unable to install package requests==2.31.0: ERROR: Cannot install requests==2.31.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts}
```

**Comment by maximuswallis** [comment]
Same issue here.

**Comment by GarthDB** [comment]
I don't know if this is what you would want to do to fix it @imhotep, but [I removed](https://github.com/GarthDB/hass-unifi-access/blob/a598fd494b05d3fda89284052a40bb5a9138a0b0/custom_components/unifi_access/manifest.json#L11) `requests` from the manifest file and it seems to work with the latest update.

**Comment by filip-heens** [comment]
Hi Garth, I’m quote new to Python but where do I find the manifest to remove the request

**Comment by filip-heens** [comment]
Hi Imothep/Garth,

I found the manifest and I did it a bit differently..
I change the
"requirements": ["websocket-client==1.6.4", "requests==2.31.0"],
To
"requirements": ["websocket-client==1.6.4", "requests>=2.31.0"],

Equal or greather than… and that also seems to work..
I think (with my little programming knowledge) that the reuests requirement will be loaded, but as I don’t know where it is used for, I don’t know if I’m doing good with it 😉
Anyway, it looks likes it’s loading now…


Filip Heens
ICT Consultant
Tel: +3224865090
[Patronale Life b.png]
Patronale Life N.V.
Verzekeringsonderneming toegelaten onder code 9081, onder toezicht van de NBB
Entreprise d’assurance agréée sous le code 1642 - Sous la surveillance de la Banque Nationale Belge
Bld. Bischoffsheimlaan 33, B-1000 Brussel / Bruxelles
www.patronale-life.be
 This e-mail and any attached files are confidential and may contain information which is protected by intellectual property rights. If you are not the addressee named above any disclosure, reproduction, copying, distribution, or other dissemination or use of this communication (including any attachment) is prohibited. If you have received this e-mail in error, please notify the sender immediately and destroy this e-mail and any copies from your system. E-mail transmission cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, and shall have no liability for any loss or damage suffered by the user, which arise as a result of e-mail transmission. The sender is validly committed only if the content of this e-mail has been accepted in writing and signed by an authorized representative, in accordance with the applicable rules on the delegation of powers.

**Comment by andrewjallen16** [comment]
Changing to "requirements": ["websocket-client==1.6.4", "requests>=2.31.0"], works great on my system. Thanks

**Comment by imhotep** [comment]
Please download the latest [v1.1.5 version](https://github.com/imhotep/hass-unifi-access/releases/tag/v1.1.5) from HACS. It has an updated version of the [requests](https://pypi.org/project/requests/) and [websocket-client](https://pypi.org/project/websocket-client/) libraries which are required for this integration to function. It has support websocket door updates (which should be quicker than before) and also hardware doorbells connected to REN terminal (this may need testing as I don't have one personally).
@GarthDB the requests library is used for initial authentication so removing it will cause some issues in case you add/delete the integration.
Also I'd advise against using `"requests>=2.31.0"` as the requests library may have some breaking changes.
Let me know if there are any issues with this new version.

**Comment by Ulrar** [comment]
I believe the issue is requests is bundled with home assistant anyway, so there's no control over the version. It's probably better to use >= and risk an unlikely breaking change rather than using == guaranteeing the integration won't load when HA updates it, IMHO

**Comment by maximuswallis** [comment]
The latest Unifi Access update above seemed to make it incompatible with home assistant core versions < 2024.6.1. FYI

**Comment by imhotep** [comment]
@maximuswallis thanks. [v1.1.6](https://github.com/imhotep/hass-unifi-access/releases/tag/v1.1.6) should work with older versions as well.

**Comment by rxin** [comment]
I noticed my UA integration was broken today for the same reason (requests version incompatibility) after a HA upgrade. And then I found the new version of this that fixed it. Thanks for updating it!

**Comment by jdgiddings** [comment]
Closing this issue due to this being fixed in the latest version
