### ISSUE TITLE
Fantom Hubs showing up in HAss

### ISSUE THREAD

**Issue by DefenestrateIT** [imhotep/hass-unifi-access#4]
In my process of learning the Access system of break/fix/break/fix/break/fix :-D

I adopted the access Hub and then deleted (forgot) it. Then I added it again, so in the Unifi Access console system, I only have one Access Hub, but in HAss (This integration), I have 2 Hubs.
This integration is seeing A phantom (deleted) Device.

I think this may be a bug with the Unifi API?

**Comment by imhotep** [comment]
It might?!

What happens when you do this?

```
curl --request GET \
  --url https://UNIFI_HOST:UNIFI_PORT/api/v1/developer/doors \
  --header 'Authorization: Bearer ACCESS_TOKEN' \
```

Replace `UNIFI_HOST`, `UNIFI_PORT` and `ACCESS_TOKEN` with your own values.

**Comment by DefenestrateIT** [comment]
`{"code":"SUCCESS","data":[{"door_lock_relay_status":"","door_position_status":"","floor_id":"b5121d33-735e-4d72-99c9-8c6534830e28","full_name":"Grandchester-UNVR-Pro - 1F - Main Door","id":"d9d9af20-0c32-4ef7-ac65-b3c28e059050","is_bind_hub":false,"name":"Main Door","type":"door"},{"door_lock_relay_status":"unlock","door_position_status":"","floor_id":"b5121d33-735e-4d72-99c9-8c6534830e28","full_name":"Grandchester-UNVR-Pro - 1F - House Back-Door","id":"2cd75b8d-982a-484a-b61f-ab20e8405f9d","is_bind_hub":true,"name":"House Back-Door","type":"door"}],"msg":"success"}`

The "Main Door" is the phantom one.

**Comment by imhotep** [comment]
@DefenestrateIT can you try v1.0.3 at let me know?

**Comment by DefenestrateIT** [comment]
So It does fix it if you reinstall the integration/Access-Host, but it doesn't remove the hub from a preinstalled integration.

This may become a problem for some people later on if you don't say they need to reinstall the integration when removing hubs from Unifi Access.

But thank you
