### ISSUE TITLE
Please add a way to treat some "doors/locks" as covers

### ISSUE THREAD

**Issue by slyglif** [imhotep/hass-unifi-access#46]
With the release of the Gate Hub, some items are now expected to be gates.  Please add the ability to either manually specific that a given device is a gate, or somehow autodetect it.  Currently it is required to "unlock" a gate to open it.

**Comment by imhotep** [comment]
It would make sense to add support for gates as covers with the Unifi Gate Hub as it seems like it's used for vehicle access. However, as said in #47 I can only accept PRs at this time since I don't have the necessary hardware to test.

**Comment by xoatrash** [comment]
+1 I would also welcome this.
