### ISSUE TITLE
Polling/refresh rate

### ISSUE THREAD

**Issue by xoatrash** [imhotep/hass-unifi-access#55]
Hi there, Is there a way to increase the refresh/polling rate for the door sensors?
Sometimes it takes up to 10 second or more until the door sensor gets the new status when a gate/door/garage is open or closed.

Thanks!

**Comment by imhotep** [comment]
Are you actually using polling? Did you tick the **_use polling_** checkbox when you configured the integration? The current setting is 3 seconds when polling is enabled and is sadly not configurable currently.
websockets (default behavior) is instantaneous and is reflected immediately.

**Comment by xoatrash** [comment]
I had to use polling because without, the door status does not change at all. :(

**Comment by imhotep** [comment]
@xoatrash the unifi gate hub is not supported. Neither is the Unifi Access Hub enterprise. @slyglif helped me add partial [support ](https://github.com/imhotep/hass-unifi-access/pull/49) and it's coming in a future release. I have neither of these hubs so it's not easy for me to support them.

**Comment by xoatrash** [comment]
Ok understood. Besides the door status problem it's working quite well already. If there is anything I can do for you, let me know.

**Comment by imhotep** [comment]
Check out v1.2.0

**Comment by xoatrash** [comment]
Unfortunately with v.1.2.0 I did not noticed any changes. :(

**Comment by imhotep** [comment]
Can you describe the exact issue you’re having and share some logs? Is it still an issue with your gate?

**Comment by xoatrash** [comment]
> Can you describe the exact issue you’re having and share some logs? Is it still an issue with your gate?

The problem is, to get the new / updated door position status when the gate opens or closes, I have to reload the whole Integration entry every time. Yep, the issue is with the Gate Hub, the normal Access Hub doe not have this issue.

<img width="1132" alt="Bildschirmfoto 2024-08-26 um 21 57 34" src="https://github.com/user-attachments/assets/d92337b1-aa5a-4c13-9842-b9324a9cc71b">

**Comment by slyglif** [comment]
I'll be able to upgrade and test it out at my place in a couple of days to verify the latest changes still work with my gate hub

**Comment by 123gizi** [comment]
Since upgrading to 1.2.0 my door lock status doesn't update with the latest lock status unless the integration is reloaded.
My DPS seems to update as required...
This is causing issues with automations when lock/unlock status is a condition for an alert when the door is opened.

Using UA Hubs for 4 doors but the issue seems to only be with the new generation Door Hub, my original UA Hub seems fine. 

![Screenshot_20240827-071457.png](https://github.com/user-attachments/assets/1127218a-b9b8-4ee5-8360-ea76f727e931)

**Comment by imhotep** [comment]
@123gizi what is the "new generation door hub"? Is it the gate hub?

**Comment by 123gizi** [comment]
@imhotep both still for doors but it seems the G2 kits had slight differences between the UA-Hub and UA-Hub-Door. This Reddit has a few images along with some peoples comments
https://www.reddit.com/r/Ubiquiti/comments/14wstma/just_received_a_mix_of_uahub_and_uahubdoor/

**Comment by imhotep** [comment]
@123gizi I see. I had never heard of it. I do not have that specific hub so cannot add support for it without some additional help. It is likely that the messages coming out of the unifi access door hub are different from the other hubs. Perhaps open another issue "support unifi access door hub" and share some debug logs. The issue described her is likely unrelated to yours (although similar).

**Comment by slyglif** [comment]
For the updates to the UGT and multiple doors on the UAH-Ent not getting processed, I think I see the problem.  When the code was refactored the part about dealing with multiple doors (the changed_doors array) wasn't pushed down into the _handle_config_update function, so it's only updating the information for the first door.  I apparently missed that part of testing when the updated patch was ready.  I'll create a PR that incorporates the functionality.

**Comment by slyglif** [comment]
Opened PR #63 to address multiple doors.  Please verify functionality on your hub (I think the update to the return line should work for that one).

**Comment by xoatrash** [comment]
> For the updates to the UGT and multiple doors on the UAH-Ent not getting processed, I think I see the problem. When the code was refactored the part about dealing with multiple doors (the changed_doors array) wasn't pushed down into the _handle_config_update function, so it's only updating the information for the first door. I apparently missed that part of testing when the updated patch was ready. I'll create a PR that incorporates the functionality.

The DPA status update works now on th UGT. :) 
It‘s not super responsive, but a good beginning. Sometimes it takes quiet a few seconds to get the new status (as polling would be activated).

**Comment by slyglif** [comment]
> > For the updates to the UGT and multiple doors on the UAH-Ent not getting processed, I think I see the problem. When the code was refactored the part about dealing with multiple doors (the changed_doors array) wasn't pushed down into the _handle_config_update function, so it's only updating the information for the first door. I apparently missed that part of testing when the updated patch was ready. I'll create a PR that incorporates the functionality.
> 
> The DPA status update works now on th UGT. :) It‘s not super responsive, but a good beginning. Sometimes it takes quiet a few seconds to get the new status (as polling would be activated).

So long as you are using websockets (haven't checked polling) it should be practically instant, or at least as instant as the UGT sees it.  Could you try turning on debug logging and paste in everything in the log for this component when you open either the gate or the door?

**Comment by xoatrash** [comment]
> > The DPA status update works now on th UGT. :) It‘s not super responsive, but a good beginning. Sometimes it takes quiet a few seconds to get the new status (as polling would be activated).
> 
> So long as you are using websockets (haven't checked polling) it should be practically instant, or at least as instant as the UGT sees it. Could you try turning on debug logging and paste in everything in the log for this component when you open either the gate or the door?

Ok, I see. It looks like the status updated would work fine. I get the correct status when the door is opened or closed for a very short time, but the UA Gate Hub is still reporting the "old" status for a pretty long time, so also HA switches back to the "wrong" sensor status. Therefore I opened a support ticket at the UniFi community.

I'll report back.

**Comment by xoatrash** [comment]
I close this for now. From your side, all looks good and is working great. Thanks for this update.
