### ISSUE TITLE
no unifi_access_doorbell_start event, UA-G2-Pro, UA-Hub and UDM-Pro

### ISSUE THREAD

**Issue by fieldsalad2** [imhotep/hass-unifi-access#58]
new Issue entry for issue originally described here: https://github.com/imhotep/hass-unifi-access/issues/52#issuecomment-2273313096

When doorbell UA-G2-Pro is rang, no unifi_access_doorbell_start event is seen on the Event Bus, nor is any other event related to the doorbell.
Access and Lock events for the same hardware (UA-G2-Pro, UA-Hub and UDM-Pro) do register properly.

Event Bus was monitored in Home Assistant (running as docker container) via the asterisk (*) mask = monitor all events.
There is no registration of any doorbell_start event while numerous other events from various other devices were registered.
Over 5 minutes of trying, 68 events, of which no doorbell events (rung 4 times).

Happy to provide any logs; please specify!

Kind regards!

**Comment by imhotep** [comment]
@fieldsalad2 can you try the latest release and let me know? If it still doesn't work, can you set the integration in debug mode. Hit the doorbell on/off a few times and share some logs here please?

Reminder this is how you enable debug mode. Add the following to your `configuration.yaml`

```
logger:
  default: info
  logs:
    homeassistant.components.unifi_access: debug
```

**Comment by imhotep** [comment]
@fieldsalad2 closing this. Feel free to re-open if you're still facing issues.

**Comment by fieldsalad2** [comment]
Seems to be fixed in the new release(s); the events are properly registered again.
I tested this by leaving out the hardwired (UA-Hub auxiliary doorbell ring output to KNX) trigger out,
only leaving the unifi_access integration doorbell_pressed event as a trigger to the doorbell ring on Sonos automation,
and it still fires the automation correctly.
I will subsequently refrain from uploading the log as the problem seems to be fixed.
Thank you!
