### ISSUE TITLE
Unclear titles for new Switches

### ISSUE THREAD

**Issue by jdgiddings** [imhotep/hass-unifi-access#59]
**Describe the bug**
The new lockdown and evacuation switches are labeled unclearly

**Which Hub are you using**
1. Unifi Access Hub

**Screenshots**

![image](https://github.com/user-attachments/assets/55dfa68c-0f10-4c79-b4b5-c994fd485feb)
![image](https://github.com/user-attachments/assets/3539966d-b2fa-464e-8bcf-607064e5db3a)
![image](https://github.com/user-attachments/assets/cac90add-89a8-483f-ba71-1c0e081c7a55)

**Versions:**
 - Home Assistant version: 2024.8.3
 - Unifi Access Integration version: v1.2.0

**Home Assistant DEBUG logs (MANDATORY)**
N/A

**Comment by xoatrash** [comment]
+1 I can confirm this.

**Comment by zacharee** [comment]
I've also got "None" appended to the names of existing entities like my hub.

**Comment by imhotep** [comment]
[v1.2.1](https://github.com/imhotep/hass-unifi-access/releases/tag/v1.2.1) should fix it. I had added support for translated strings and forgot to add the strings file.
The entities won't be automatically renamed though unless you remove/add integration again. So you'd need to rename them manually
By the way, for those of you who use Home Assistant in a language other than English, you could contribute to this integration by translating this [file](https://github.com/imhotep/hass-unifi-access/blob/main/custom_components/unifi_access/translations/en.json) and you'd have this integration support your language.

**Comment by xoatrash** [comment]
Thanks for the update, I could do german and italian translations. 👍

**Comment by imhotep** [comment]
@xoatrash that would be incredible! Are you familiar with submitting pull requests on github?

**Comment by jdgiddings** [comment]
> [v1.2.1](https://github.com/imhotep/hass-unifi-access/releases/tag/v1.2.1) should fix it. I had added support for translated strings and forgot to add the strings file. The entities won't be automatically renamed though unless you remove/add integration again.

Mine updated themselves! 

![image](https://github.com/user-attachments/assets/3a0a44df-5704-443c-b29e-ffb43052f01d)

**Comment by imhotep** [comment]
@jdgiddings entity_id's... the names do update themselves indeed, that was the purpose of this fix :)

**Comment by jdgiddings** [comment]
That makes more sense. Thanks!

**Comment by imhotep** [comment]
Closing. @xoatrash look forward to those `it` and `de` translations ;)

**Comment by filip-heens** [comment]
Hi Anis,

I could help with a Dutch translation
I could send it to you or if you want me to upload it, just let me know 😉

Filip

**Comment by imhotep** [comment]
@filip-heens I’d prefer a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) against this repository but if you want to send me the file, I can use it too!

**Comment by filip-heens** [comment]
Did a pull request (ok checked that on the to do list.. make my first pull request on github 😃)

Filip Heens
ICT Consultant
Tel: +3224865090
[Patronale Life b.png]
Patronale Life N.V.
Verzekeringsonderneming toegelaten onder code 9081, onder toezicht van de NBB
Entreprise d’assurance agréée sous le code 9081 - Sous la surveillance de la Banque Nationale Belge
Bld. Bischoffsheimlaan 33, B-1000 Brussel / Bruxelles
www.patronale-life.be
 This e-mail and any attached files are confidential and may contain information which is protected by intellectual property rights. If you are not the addressee named above any disclosure, reproduction, copying, distribution, or other dissemination or use of this communication (including any attachment) is prohibited. If you have received this e-mail in error, please notify the sender immediately and destroy this e-mail and any copies from your system. E-mail transmission cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, and shall have no liability for any loss or damage suffered by the user, which arise as a result of e-mail transmission. The sender is validly committed only if the content of this e-mail has been accepted in writing and signed by an authorized representative, in accordance with the applicable rules on the delegation of powers.
