### ISSUE TITLE
Intercom doorbell notifications

### ISSUE THREAD

**Issue by malikmalikmalik** [imhotep/hass-unifi-access#69]
**Describe the bug**
HA is not registering the doorbell presses.
When looking at the logbook, it only shows the door as unlocked, then an event, then the door locked. (this is when unlocking the electric lock through Access).
When opening the door manually after someone rings it, nothing gets registered.

I can attach logs if needed, but I want to understand if Intercom is considered a different/unsupported doorbell for this integration. I read some closed issues in this repo, but it's still not clear.

**Which Hub are you using**
Unifi Access Hub
Running the setup as required by UI. Intercom attached to an PoE++ powered Access Hub attached to a console (UDM-Pro)

**Versions:**
 - Home Assistant version 2024.8.3
 - Unifi Access version 2.2.11
 - Unifi Access Integration version 1.2.3

**Comment by imhotep** [comment]
The intercom is **NOT** supported. It could be supported but I would need some debug logs as I don't own the device myself. My understanding is that the open/close events are working properly but the doorbell events are not. So I would need you to:
- Start logging
- Ring the doorbell, wait a few seconds, cancel it.
- Stop logging

Attach those logs to this issue and I will be happy to take a look.

Reminder:
The easiest way to download logs is by toggling Enable/Disable debug logging. 

![unifi access logs](https://github.com/user-attachments/assets/775708bf-6645-4a4a-97f3-b59607665e8a)

**Comment by malikmalikmalik** [comment]
Well that's clear, thanks.

Here are the logs:
[home-assistant_unifi_access_2024-09-02T18-03-08.600Z.log](https://github.com/user-attachments/files/16840409/home-assistant_unifi_access_2024-09-02T18-03-08.600Z.log)

I do have to say, I've been trying to get the unifi_access_doorbell_start event all weekend and now that I turn the DEBUG on, it triggered.

To test the trigger, I created a small automation using the binary_sensor.front_door_hub_doorbell "when occupied".
I've had 6 doorbell rings today, none of them triggered the automation. But the ring with debug on, triggered the automation for the first time.

<img width="562" alt="Screenshot 2024-09-02 at 20 09 00" src="https://github.com/user-attachments/assets/157dd5ff-09ae-4c4b-a699-3fe68ad5b2f7">

Very strange.

Let me know if I can do more tests.

**Comment by imhotep** [comment]
@malikmalikmalik according to those logs, your doorbell presses are getting registered correctly. Did you enable polling when setting up the integration? Doorbell Presses are not supported when polling is enabled. 
Enabling debug logs doesn't change anything functionally.

**Comment by malikmalikmalik** [comment]
No polling, no SSL (for now).

I have no idea what changed though.
Now the logbook started showing events for the doorbell press.
![IMG_0732](https://github.com/user-attachments/assets/7a323c47-a58f-4979-b37e-a0f479d52829)

That’s good news in the logbook, just not sure if it’s reliable. In any case, it’s an extra. I have unifi viewers, but it would be nice to add some other actions in HA.

I’ll keep an eye out for the events and wait for an update.

Happy to do more tests if necessary! And thank you👌🏻

**Comment by imhotep** [comment]
@malikmalikmalik can you please try v1.2.4?

**Comment by malikmalikmalik** [comment]
Thank you Anis.

If updated the integration and did another debug log of ring, cancel, unlock.
HA does 2 things now on a doorbell press:
Front Door Doorbell detects occupancy
Front Door Doorbell Press detects an event

On cancel, it looks like HA clears the occupancy and then registers another "event".
Front Door Doorbell cleared (no occupancy detected)
Front Door Doorbell Press detected an event

That works for me.


[home-assistant_unifi_access_2024-09-03T07-17-47.657Z.log](https://github.com/user-attachments/files/16844952/home-assistant_unifi_access_2024-09-03T07-17-47.657Z.log)

Nicely done!

**Comment by imhotep** [comment]
@malikmalikmalik awesome! Closing this for now!
