### ISSUE TITLE
Authentication Type for Access Event

### ISSUE THREAD

**Issue by jblattel** [imhotep/hass-unifi-access#71]
Hello and thanks for all of your work. I was wondering if you could expose the authentication_type to the Access Event. I believe the API supports this here:

        "actor": {
            "id": "d62e92fd-91aa-44c2-9b36-6d674a4b74d0",
            "name": "Hon***",
            "type": "user"
        },
        "object": {
            "authentication_type": "CALL", //Door opening method, NFC/PIN_CODE/Call For a DoorBell
            "authentication_value": "",
            "policy_id": "",
            "policy_name": "",
            "reader_id": "",
            "result": "Access Granted"
        }

This way we can determine how access was granted and e.g. take action for remotely authorized access vs say a phone tap. Or better way to look at it an unknown user that has been granted access via the actor or the actor him/herself tapping in. 

I thought I'd take a stab at working on this myself but my level of understanding of HA is basically NILL. 

Thanks again.

**Comment by jblattel** [comment]
Update:
I looked at your code again - and realize (or think rather) you're getting actor info from the add log event and not the access.unlock.door webhook. Therefore, I amend above to utilize:

```
"data": {
        "hits": [
            {
                "@timestamp": "2023-07-11T12:11:27Z",
                "_id": "",
                "_source": {
                    "actor": {
                        "alternate_id": "",
                        "alternate_name": "",
                        "display_name": "N/A",
                        "id": "",
                        "type": "user"
                    },
                    "authentication": {
                        "credential_provider": "NFC",
                        "issuer": "6FC02554"
                    },
```

I'm not sure what "credential_provider" all entails but may be able to get the same information from there? Maybe something like:

```
if door_id in self.doors:
                            existing_door = self.doors[door_id]
                            actor = update["data"]["_source"]["actor"]["display_name"]
                            authentication =update["data"]["_source"]["authentication"]["credential_provider"]
                            device_config = next(
                                (
                                    target
                                    for target in update["data"]["_source"]["target"]
                                    if target["type"] == "device_config"
                                ),
                                None,
                            )
                            if device_config is not None:
                                access_type = device_config["display_name"]
                                event = "access"
                                event_attributes = {
                                    "door_name": existing_door.name,
                                    "door_id": door_id,
                                    "actor": actor,
                                    "authentication": authentication,
                                    "type": ACCESS_EVENT.format(type=access_type),
                                }
```

Thanks!

**Comment by imhotep** [comment]
@jblattel this integration uses websockets for status updates as you came to find out. The problem is supporting this across multiple UA hubs as they all have different (and undocumented) messages.

**Comment by jblattel** [comment]
I'm guessing they are the 3 they indicated (NFC, CALL and PIN_CODE) at least for the door[id] ... authentication.credential_provider - but yeah there is no mention of that really anywhere in the doc. I may go ahead and take a stab at implementing this. Least take a look at the raw logging coming out of the event and test those 3 parameters. Less there's some other hidden code it looks like those event objects and associated attributes just get put up onto the HA bus, so fairly straightforward.

**Comment by imhotep** [comment]
@jblattel yeah if it's just about adding a property to the event. It should be as simple as getting the property from the "access.logs.add" websocket [message](https://github.com/imhotep/hass-unifi-access/blob/main/custom_components/unifi_access/hub.py#L566) and adding it to the event [attributes](https://github.com/imhotep/hass-unifi-access/blob/main/custom_components/unifi_access/hub.py#L593-L598)

**Comment by jblattel** [comment]
OK - here is the [PR](https://github.com/imhotep/hass-unifi-access/pull/75) - I'm not sure I've covered all cases but certainly enough to make the attribute actionable on .... :)

**Comment by jblattel** [comment]
@imhotep  - I see you merged the changed awesome - will close this.
