### ISSUE TITLE
Ubiquiti Intercom Limited Support Documentation or Directions and Testing

### ISSUE THREAD

**Issue by jasonhollis** [imhotep/hass-unifi-access#73]
Team,

I noticed the limited/experimental support for Intercoms.  I have two in a system running 1.24.  Is there anyway to understand what support is there how to leverage it or how I can help with the testing?

**Comment by jasonhollis** [comment]
Team,

I just read the docs and I have probed the API on the DMP and got this response from a list devices:

{"code":"SUCCESS","data":[[{"id":"9c05d6cddc4f","name":"UA Intercom Viewer dc4f","type":"UA-Int-Viewer"}],[{"id":"9c05d6c24080","name":"UA Intercom Viewer 4080","type":"UA-Int-Viewer"}],[{"id":"d8b3707d2b41","name":"UA Hub","type":"UAH"},{"id":"f4e2c6bceaf1","name":"UA-G2-Black-eaf1","type":"UA-G2-MINI"}],[{"id":"d8b3707d2f71","name":"UA Hub","type":"UAH"},{"id":"f4e2c6f41839","name":"UA G2 Pro Black 1839","type":"UA-G2-PRO"}]],"msg":"success"}

**Comment by jasonhollis** [comment]
I generated a new API Token and built a new entry and I do see references to an intercom pair in the logs but not a lot more.  My current issue is that folks don't always know how to ring the doorbell on the G2 Pro.  I have setup and automation with a Webhook in protect that lets me know from the cameras when someone is walking up to the door.  I now want to send something to the intercoms alerting to the fact that there is someone standing at the door.

**Comment by imhotep** [comment]
> I noticed the limited/experimental support for Intercoms. I have two in a system running 1.24. Is there anyway to understand what support is there how to leverage it or how I can help with the testing?

I have no idea. I don't have the device myself and currently it's treated as a UAH as the API messages look similar. If something is not working as expected, feel free to create an issue and share some debug logs.

> I now want to send something to the intercoms alerting to the fact that there is someone standing at the door.

This integration doesn't currently interact with the video feeds nor does it communicate with the intercom viewers so it probably won't be useful to you. You may have better luck with the Protect [automations](https://help.ui.com/hc/en-us/articles/25478744592023-Send-UniFi-Protect-Alerts-to-Web-Services-using-Webhooks) and home assistant [webhooks](https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger). It seems like you may be already using those?
