### ISSUE TITLE
Lock status not showing correctly in Home Assistant 

### ISSUE THREAD

**Issue by iandogherty** [imhotep/hass-unifi-access#74]
**Describe the bug**
Lock status always shows locked despite successful locks and unlocks from Home Assistant

**Which Hub are you using**
1. Unifi Access Hub

**Versions:**
 - Home Assistant version 2024.9.1
 - Unifi Access version (Go to settings in your Unifi Access web interface) 2.2.11
 - Unifi Access Integration version [latest
[home-assistant_unifi_access_2024-09-05T08-07-54.237Z.zip](https://github.com/user-attachments/files/16944853/home-assistant_unifi_access_2024-09-05T08-07-54.237Z.zip)

**Home Assistant DEBUG logs (MANDATORY)**
Provide logs

**Comment by xoatrash** [comment]
Do you habe this problem only since the latest Ha Access version 1.2.4?
I have a similat issue, my door status sensor is closed, but in HA it constantly changes from closed to open, an back again? 
I switched back to 1.2.3, and it‘s working there.

**Comment by iandogherty** [comment]
I'm .23 it would unlock, show unlocked, but then stay as showing unlocked!

**Comment by imhotep** [comment]
@iandogherty you seem to be using the unifi gate hub which sadly I don't have in my posession so can't test it.
There are also two problems with those logs
1. you are using polling. please remove the integration and re-add it without enabling "use polling". See if that helps.
2. those logs are not debug logs and also include a bunch of unrelated items. Please follow the steps [here](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging) to get actual debug logs.

**Comment by iandogherty** [comment]
hey - reinstalled with polling off and it works! thanks for all your help
