### ISSUE TITLE
Intercom support

### ISSUE THREAD

**Issue by stuartford** [imhotep/hass-unifi-access#81]
The notes about Intercom support being "partial/experimental" are fully noted.

I've the following questions with this in mind:

1. Can we access the experimental features?
2. When do you expect support will be added?

**Comment by dodavies** [comment]
I have just deployed the Unifi hub and intercom so support would be awesome, thanks for your work

**Comment by imhotep** [comment]
1. yes, the integration should already support basic intercom features. If you are facing issues, please open a more specific ticket.
2. probably never unless someone who owns the UA-intercom (which I don't) can add support for it and keep supporting it. Sorry for the inconvenience.

**Comment by dodavies** [comment]
I have an intercom if I can help with it but I don’t code Sent from my iPhoneOn 31 Oct 2024, at 16:50, Anis Kadri ***@***.***> wrote:﻿

yes, the integration should already support basic intercom features. If you are facing issues, please open a more specific ticket.
probably never unless someone who owns the UA-intercom (which I don't) can add support for it and keep supporting it. Sorry for the inconvenience.

**Comment by dodavies** [comment]
I have noticed that if the intercom is in a standby situation and you access it from the access app it causes a false trigger on the dps, I previously believed this was a sensor issue but I have linked the dps pins with a piece of wire, if I go to open the camera in access dps triggers an opened event

**Comment by imhotep** [comment]
Can you share some logs of when that happens?

**Comment by dodavies** [comment]
Please see issue 84Sent from my iPhoneOn 13 Nov 2024, at 13:18, Anis Kadri ***@***.***> wrote:﻿
Can you share some logs of when that happens?
