### ISSUE TITLE
Detect which method was used to unlock door (NFC, PIN, MOBIILE)

### ISSUE THREAD

**Issue by veeds2** [imhotep/hass-unifi-access#82]
First, I really appreciate the work you have done with Access & HA. It is good to know others are using the same technology!

Would it be possible to also contain an attribute describing the type of method that was used to unlock the door (nfc,pin,mobile etc)?

For example   
new_state: object
  attributes: object
    access_method: {"pin","mobile","nfc"}

This would really help determine if a new guest came in and used a PIN or an existing guest came back and used an NFC card. 

Thank you!

**Comment by imhotep** [comment]
Yes. It's [coming](https://github.com/imhotep/hass-unifi-access/pull/75) in an upcoming release.
