### ISSUE TITLE
Unable to see Intercom faeatures

### ISSUE THREAD

**Issue by stuartford** [imhotep/hass-unifi-access#83]
**Describe the bug**

As you requested in: https://github.com/imhotep/hass-unifi-access/issues/81#issuecomment-2450358600

I cannot see any devices or entities relating to the Intercom in the integration. I an aware these features are experimental. How do I see them?

**Which Hub are you using**

Unifi Access Hub

**Screenshots**

![Screenshot 2024-11-06 at 15 36 07](https://github.com/user-attachments/assets/f5882fcf-398e-4e72-9a74-c1655651fa3c)
![Screenshot 2024-11-06 at 15 36 23](https://github.com/user-attachments/assets/3dce59f4-1674-4dbf-9be5-683610fa1d42)
![Screenshot 2024-11-06 at 15 36 36](https://github.com/user-attachments/assets/60f0476b-8c8b-4711-804f-d578c01f3b59)

**Versions:**

 - Home Assistant version: 2024.10.4
 - Unifi Access version: 2.4.7
 - Unifi Access Integration version: 1.2.4

**Comment by imhotep** [comment]
According to your screenshot, the [supported](https://github.com/imhotep/hass-unifi-access?tab=readme-ov-file#installation-hacs) entities are shown correctly. It seems like you have one hub called "UA Hub". Are you expecting to see other types of entity?

**Comment by stuartford** [comment]
Hi Anis

Thank you for your reply.

It is fully acknowledged and accepted that Intercom support is "partial/experimental".

In issue 81, I asked "Can we access the experimental features?", to which you replied "yes, the integration should already support basic intercom features. If you are facing issues, please open a more specific ticket", which is what I have done, because I cannot see any Intercom-related features, devices or entities.

Having looked more closely, however, I can see that the entity "UA Hub Doorbell [Press]" entities may be the one I am looking for. I did not initially inspect this because I assumed that this would relate to something else, given it's not labelled Intercom in any way.

Many thanks for your assistance :)
