### ISSUE TITLE
Gate reported as open even it is closed

### ISSUE THREAD

**Issue by xoatrash** [imhotep/hass-unifi-access#87]
Since v.1.2.4 I have the issue, that my gate changes it's status back to open after 1-2 minutes or so, even the gate is still closed. This is not a sensor problem. The same issue occurs also with the latest v.1.2.5 release.

1.2.3 was the latest without that issue.

**Comment by imhotep** [comment]
@xoatrash please answer the questions in the issue template and provide some logs.
