### ISSUE TITLE
Notification on ring pressed

### ISSUE THREAD

**Issue by techunleadit** [imhotep/hass-unifi-access#9]
Hi,
there is the possibility to have a binary_sensor or something else to know when the ringbell is pressed?

Thanks for your awesome work

**Comment by imhotep** [comment]
@techunleadit there is a binary sensor in the latest version when using websockets (default).  Do you not see it?

**Comment by techunleadit** [comment]
@imhotep yes but when someone press the ringbel is not changing status. Do you want to have access to a test HA instance?
![image](https://github.com/imhotep/hass-unifi-access/assets/93933385/2ff7c9a9-7daf-4313-9f57-592aa9217e5b)

**Comment by ethank** [comment]
@techunleadit also confirming that with the newest version, the binary sensor isn't changing when the ring is triggered on the access

**Comment by techunleadit** [comment]
@imhotep I forgot to tell you that I have Access 1.22.10 as my version

@ethank referring to the documentation, paragraph "8.2 Fetch Device Notifications", is it possible that something has changed with my version? Because this should be the payload they say on the documentation:

> WebSocket Payload

`When a doorbell rings: [access.remote_view]
Doorbell status change: [access.remote_view.change]
{
 "event": "access.remote_view",
 "receiver_id": "",
 "event_object_id": "535b6125-860c-489a-b0a1-0ba01906afa9",
 "save_to_history": false,
 "data": {
 "channel": "4513899f-0370-4116-9731-63a6b0feea23",
 "token": "6dff120f-2688-497d-856f-0ca08b383d1d",
 "device_id": "e4388386be1d",
 "device_type": "UA-G2-PRO",
 "device_name": "UA-G2-PRO-BE1D"`

**Comment by ethank** [comment]
I'm on 1.22.10 as well, but the binary sensor is not changing when the ring is pressed. Confirmed again today.

**Comment by imhotep** [comment]
Fixed in [1.1.2](https://github.com/imhotep/hass-unifi-access/releases/tag/v1.1.2). reopen the issue if it still doesn't work
